name = "Vanilla Create"
author = "Souldbminer"
version = "5.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d30de1aa4d9fc2b3c7e8bd503c5622ab179530a3a18490a9a159642a43a89ea"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
