name = "Vanilla Create"
author = "Souldbminer"
version = "5.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46f89a230d06bf9d393584e3d179e7f1aa321864e26eba8df22d56acaaeabb87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
