name = "Vanilla Create"
author = "Souldbminer"
version = "5.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f42dfd4d54cae860151c16ea689eea22b4cd30ab85b3f51fe32b5e9a67371d21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
