	[tweaks.enchanting]
		#Allow enchanting power from bookshelves to transmit through any non-solid block, not just replaceable ones
		"Non-solid blocks transmit enchanting power" = true
		#Allow Chiseled Bookshelves to be usable to boost enchanting table power
		"Chiseled Bookshelf enchanting" = true
		#How many regular books are needed to increase the enchantment power by 1
		# Default: 3
		# Range: 1 ~ 6
		"Books needed" = 3
		#How many enchanted are needed to increase the enchantment power by 1
		# Default: 2
		# Range: 1 ~ 6
		"Enchanted Books needed" = 2

	[tweaks.bane_of_arthropods]
		#If Bane of Arthropods increases the mining speed of Cobwebs
		"Bane of Arthropods mines cobwebs faster" = true

	[tweaks.feather_falling]
		#If having Feather Falling prevents farmland from being trampled
		"Feather Falling prevents trampling" = true

	[tweaks.infinity]
		#If Infinity requires an arrow in the player's inventory in order to shoot
		"Infinity requires arrows" = false

	[tweaks.riptide]
		#Allow Riptide to function when in cauldrons
		"Riptide works in cauldrons" = true

	[tweaks.soul_speed]
		#Instead of losing durability as you run, Soul Speed makes incoming damage increase when on Soul Speed blocks
		"Soul Speed change" = true

		[tweaks.experience.dropped_xp]
			#If the player drops a flat percentage of their experience rather than capping at level 7
			"Drop experience percentage" = false
			#What percentage of the player's total experience is dropped
			# Default: 0.75
			# Range: 0.0 ~ 1.0
			"Experience percentage" = 0.75

		[tweaks.experience.level_scaling]
			#Remove the amount of experience per level increasing (experimental)
			"Remove level scaling" = false
			#The amount of experience per level, if level scaling is removed (experimental)
			# Default: 50
			# Range: > 0
			"Experience per level" = 50
			#If the level scaling should only be modified after it reaches the 'Experience per level' value (experimental)
			"Remove level scaling after cap" = true

		[tweaks.experience.ender_dragon]
			#If Ender Dragon experience dropping should be adjusted (to account for level scaling)
			"Adjust Ender Dragon experience drop" = false
			#The amount of experience (in points) that should be dropped by the Ender Dragon
			# Default: 3000
			# Range: > 0
			"Ender Dragon experience drop" = 3000
			#The amount of experience (in points) that should be dropped by a respawned Ender Dragon
			# Default: 750
			# Range: > 0
			"Respawned Ender Dragon experience drop" = 750

		[tweaks.experience.anvil]
			#If renaming items should always cost 1 experience
			"Cheap item renaming" = true
			#Remove the cap of 40 on anvil repairing prices
			"Remove too expensive" = true
			#If anvils can be repaired by right clicking with an iron ingot or using a dispenser
			"Anvil ingot repairing" = true
			#The amount of tries it should take on average to repair an anvil with an ingot (1 in x chance)
			# Default: 5
			# Range: > 0
			"Ingot repair chance" = 5
			#If anvil transaction costs should be capped at a certain level
			"Cap anvil costs" = false
			#The max amount of levels an anvil transaction should be able to cost
			# Default: 30
			# Range: > 1
			"Anvil cost cap" = 30

	[tweaks.animal_armor]
		#Allow animal armor to be enchanted
		"Enchantable animal armor" = true
		#If animal armor can appear enchanted when found in loot tables
		"Generates in loot tables" = true
		#Which loot tables animal armor can't appear enchanted in
		"Unenchanted loot tables" = ["minecraft:chests/village/village_weaponsmith", "minecraft:chests/stronghold_corridor", "minecraft:chests/nether_bridge"]
