#Whether to allow factory gauges cascade ingredient requests
factoryGaugeCascadeRequest = true
#Capacity of the jar in millibuckets
# Default: 1000
# Range: 1 ~ 999999999
jarCapacity = 1000
#Whether jar packager (bottler) should pick output tanks over combined. Useful if you want to keep basin inputs intact
jarPackagerPrefersOutputs = true
