# default: true
biomeWater = true
# default: true
topography = true
# default: true
transparentWater = true
# default: true
lighting = true
# default: true
showOffline = true
# default: true
renderBorder = true
# default: true
renderOutsideBorder = true
