version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
arts_and_crafts = true
farmersdelight = true
create_mechanical_extruder = true
somemoreblocks = true
excavated_variants = true
nomansland = true
trailandtales_delight = true
ribbits = true
clayworks = true
another_furniture = true
friendsandfoes = true
copycats = true
no_mans_delight = true
chalk = true
sootychimneys = true
create_enchantment_industry = true
bellsandwhistles = true
berry_good = true
marigolds = true
buzzier_bees = true
mynethersdelight = true
cavern-root = true
vanillabackport = true
createeggproduction = true
exposure = true
renether = true
tiny-flowers = true
delivery_director = true
endersdelight = true
create_vibrant_vaults = true
mo_glass = true
incubation = true
woodworks = true
create = true
resource_backpacks = true
minecraft = true
create_dragons_plus = true
rusticdelight = true
create_connected = true
create_jetpack = true
trading_floor = true
create_mobile_packages = true
createframed = true
crabbersdelight = true
create_d2d = true
creategarnished = true
create_aquatic_ambitions = true
netherdepthsupgrade = true
pipeorgans = true
create_integrated_farming = true
create_power_loader = true
